### ISSUE TITLE
{{ getWordCount(content) }} always prints zero

### ISSUE THREAD

**Issue by Wavesonics** [dimitrilongo/grav-plugin-wordcount#2]
Putting this at the top or bottom of my content always prints 0

Maybe I am misunderstanding it's purpose? I would exact it to give me the word count for the content of the page.

Example:
http://readwriterepeat.net/story-00/chapter-0

**Comment by dimitrilongo** [comment]
for example in antimatter theme you have to put the twig function in default.html.twig

````{{ getWordCount(page.content) }}````
it returns the word count, or you can set a var
````{% count_word = getWordCount(page.content) %}```` and then you can print the wordcount anywhere in your twig ````{{ count_word) }}````
